#!/bin/bash
if [[ -z "$1" ]] 
  then
  KEYROOT=$HOME
else
  KEYROOT=$1
fi

gem install ejson

ejson --keydir=$KEYROOT/.ejson decrypt config/secrets.production.ejson > config/secrets.json

docker build -t tohtori .

rm -rf config/secrets.json
